version: '3'
services:
   web:
     build: ./app
     ports:
       - "5000:5000"
     networks:
       - webapp
   redis:
     image: redis
     ports:
       - "6379:6379"
     networks:
       - webapp
   mongo:
     image: mongo
     ports: 
       - "27017:27017"
     volumes:
       - mongo_data:/data/db
     networks:
       - webapp

volumes:
   mongo_data:
     driver: local
networks:
   webapp:
     driver: bridge
