---

- hosts: dbservers
  become: true
  tasks:
    - name: "Add MongoDB apt key"
      apt_key:
        keyserver: "hkp://keyserver.ubuntu.com:80"
        id: "0C49F3730359A14518585931BC711F9BA15703C6"
        state: present
    - name: "Add MongoDB apt repository"
      apt_repository:
        repo: "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse"
        state: present
    - name: "Install MongoDB"
      apt:
        name: mongodb-org
        state: installed
        update_cache: yes
    - name: "Start mongod"
      service:
        name: mongod
        state: started


