---

- hosts: webservers
  become: true
  vars_files:
    - ./variables.yml
  tasks:
    - name: find the files in the home directory
      shell: "ls -lah {{ home }}"
    - name: create the picture folder
      file:
        path: "{{ pictures_folder }}"
        state: directory

