# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.define "redhat-node" do |redhat|
		redhat.vm.box = "bento/centos-7.2"
		redhat.vm.hostname = "redhat-node"
		redhat.vm.network :private_network, ip: "10.10.10.14"
		redhat.vm.provider "virtualbox" do |vb|
			vb.memory = "256"
		end
		redhat.ssh.insert_key = false
	end

	(1..3).each do |i|
	   config.vm.define "node#{i}" do |node|
		   node.vm.box = "bento/ubuntu-16.04"
		   node.vm.hostname = "node#{i}"
		   node.vm.network :private_network, ip: "10.10.10.1#{i}"
		   node.vm.provider "virtualbox" do |vb|
				vb.memory = "256"
		   end
		   
	   end

	end
	config.vm.define "controller" do |controller|
		controller.vm.box = "bento/ubuntu-16.04"
		controller.vm.hostname = "controller"
		controller.vm.network :private_network, ip: "10.10.10.10"
		controller.vm.provider "virtualbox" do |vb|
			vb.memory = "256"
		end
		controller.vm.provision :shell, path: 'ubuntu-setup.sh'
	end

	
	
end
