---

- hosts: webservers
  become: true
  gather_facts: no
  vars:
    sample: 10
  tasks:
    - name: install apache2 
      apt:
        name: apache2
        state: present
    - name: start apache2 
      service:
        name: apache2
        state: started
    - name: install libapache2-mod-python
      apt:
        name: libapache2-mod-python
        state: present
      notify: restart apache 
    - name: install  libapache2-mod-wsgi
      apt:
        name: libapache2-mod-wsgi
        state: present
      notify: restart apache
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      
         
