---

- hosts: webservers
  become: true
  vars:
    required_packages:
      - git
      - zsh
      - vim
      - nodejs 
    required_packages_as_objects:
      - name: git
        state: present
      - name: zsh
        state: present
      - name: vim
        state: present
      - name: nodejs
        state: present
  tasks: 
    - name: install packages
      apt: 
        name: "{{ item }}"
        state: present
      with_items: "{{ required_packages }}"

