version: '3'
services:
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
    networks:
      - webapp
    deploy:
      placement:
        constraints: [node.role == manager]
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - webapp
    deploy:
      placement:
        constraints: [node.role == manager]
  app:
    image: justindevpro/pythonweb
    ports:
      - "5000:5000"
    networks:
      - webapp
    depends_on:
      - redis
      - mongo
    deploy:
      mode: replicated
      replicas: 2

networks:
  webapp:
    driver: overlay

volumes:
  mongo_data:








#
#
